// Generated by tools/gen_assets.py — do not edit.
#pragma once
#include <Arduino.h>

#define ICON_W 64
#define ICON_H 64

extern const uint16_t ic_power[4096] PROGMEM;
extern const uint16_t ic_vol_up[4096] PROGMEM;
extern const uint16_t ic_vol_down[4096] PROGMEM;
extern const uint16_t ic_unmuted[4096] PROGMEM;
extern const uint16_t ic_muted[4096] PROGMEM;
extern const uint16_t ic_up[4096] PROGMEM;
extern const uint16_t ic_down[4096] PROGMEM;
extern const uint16_t ic_left[4096] PROGMEM;
extern const uint16_t ic_right[4096] PROGMEM;
extern const uint16_t ic_ok[4096] PROGMEM;
extern const uint16_t ic_back[4096] PROGMEM;
extern const uint16_t ic_home[4096] PROGMEM;
extern const uint16_t ic_exit[4096] PROGMEM;
extern const uint16_t ic_settings[4096] PROGMEM;
extern const uint16_t ic_play[4096] PROGMEM;
extern const uint16_t ic_pause[4096] PROGMEM;
extern const uint16_t ic_screen_off[4096] PROGMEM;
extern const uint16_t ic_screen_on[4096] PROGMEM;
extern const uint16_t ic_input[4096] PROGMEM;

// Generated HDMI input tiles
extern const uint16_t ic_hdmi1[4096] PROGMEM;
extern const uint16_t ic_hdmi2[4096] PROGMEM;
extern const uint16_t ic_hdmi3[4096] PROGMEM;
extern const uint16_t ic_hdmi4[4096] PROGMEM;

// App art, keyed by webOS app id
struct AppArt { const char* id; const uint16_t* icon; };
#define APP_ART_COUNT 18
extern const AppArt APP_ART[APP_ART_COUNT];

extern const uint16_t app_netflix[4096] PROGMEM;
extern const uint16_t app_youtube_leanback_v4[4096] PROGMEM;
extern const uint16_t app_com_disney_disneyplus_prod[4096] PROGMEM;
extern const uint16_t app_amazon[4096] PROGMEM;
extern const uint16_t app_com_apple_appletv[4096] PROGMEM;
extern const uint16_t app_bbc_iplayer_3_0[4096] PROGMEM;
extern const uint16_t app_com_fvp_itv[4096] PROGMEM;
extern const uint16_t app_com_channel4_ondemand[4096] PROGMEM;
extern const uint16_t app_demand5[4096] PROGMEM;
extern const uint16_t app_now_tv[4096] PROGMEM;
extern const uint16_t app_com_webos_app_igallery[4096] PROGMEM;
extern const uint16_t app_spotify_beehive[4096] PROGMEM;
extern const uint16_t app_plex[4096] PROGMEM;
extern const uint16_t app_com_webos_app_livetv[4096] PROGMEM;
extern const uint16_t app_airplay[4096] PROGMEM;
extern const uint16_t app_com_webos_app_photovideo[4096] PROGMEM;
extern const uint16_t app_com_webos_app_music[4096] PROGMEM;
extern const uint16_t app_com_bskyb_skystore[4096] PROGMEM;
