#!/usr/bin/env python3
"""Convert Stream Deck plugin PNG artwork into RGB565 C arrays for TFT_eSPI.

Reads 144x144 key art from the lgtv-streamdeck plugin, composites it over
black, resizes to ICON px, and writes src/assets.cpp + include/assets.h.
"""
import sys, pathlib
from PIL import Image

PLUGIN = pathlib.Path("/Users/garyriches/Documents/.Source.nosync/lgtv-streamdeck/mobi.bouncingball.smartremote.sdPlugin/imgs")
ROOT = pathlib.Path(__file__).resolve().parent.parent
ICON = 64
RADIUS = 12   # rounded-corner radius at ICON px, applied to every tile (the screen bg is black)

# (c identifier, relative png path)
ACTIONS = [
    ("ic_power",      "actions/power/key.png"),
    ("ic_vol_up",     "actions/volume-up/key.png"),
    ("ic_vol_down",   "actions/volume-down/key.png"),
    ("ic_unmuted",    "actions/mute/unmuted.png"),
    ("ic_muted",      "actions/mute/muted.png"),
    ("ic_up",         "actions/nav/up.png"),
    ("ic_down",       "actions/nav/down.png"),
    ("ic_left",       "actions/nav/left.png"),
    ("ic_right",      "actions/nav/right.png"),
    ("ic_ok",         "actions/nav/ok.png"),
    ("ic_back",       "actions/nav/back.png"),
    ("ic_home",       "actions/nav/home.png"),
    ("ic_exit",       "actions/nav/exit.png"),
    ("ic_settings",   "actions/nav/settings.png"),
    ("ic_play",       "actions/playpause/play.png"),
    ("ic_pause",      "actions/playpause/pause.png"),
    ("ic_screen_off", "actions/screen/off.png"),
    ("ic_screen_on",  "actions/screen/on.png"),
    ("ic_input",      "actions/input/key.png"),
]

# webOS app ids whose art we bundle (identifier derived from the id)
APPS = [
    "netflix", "youtube.leanback.v4", "com.disney.disneyplus-prod", "amazon",
    "com.apple.appletv", "bbc.iplayer.3.0", "com.fvp.itv", "com.channel4.ondemand",
    "demand5", "now.tv", "com.webos.app.igallery", "spotify-beehive",
    "plex",
    "com.webos.app.livetv", "airplay", "com.webos.app.photovideo", "com.webos.app.music",
    "com.bskyb.skystore", "mubi", "lgchannels.uk", "com.palm.app.settings",
]

def cname(app_id):
    return "app_" + "".join(c if c.isalnum() else "_" for c in app_id)

def rounded_mask(size, radius):
    # Supersampled for smooth anti-aliased corners.
    from PIL import ImageDraw
    ss = 4
    m = Image.new("L", (size * ss, size * ss), 0)
    ImageDraw.Draw(m).rounded_rectangle([0, 0, size * ss - 1, size * ss - 1], radius=radius * ss, fill=255)
    return m.resize((size, size), Image.LANCZOS)

_MASK = None

def to_rgb565(path):
    global _MASK
    if _MASK is None:
        _MASK = rounded_mask(ICON, RADIUS)
    im = Image.open(path).convert("RGBA")
    im = im.resize((ICON, ICON), Image.LANCZOS)
    # Clip to a rounded rectangle, then flatten onto black.
    a = im.getchannel("A")
    from PIL import ImageChops
    im.putalpha(ImageChops.multiply(a, _MASK))
    bg = Image.new("RGBA", im.size, (0, 0, 0, 255))
    im = Image.alpha_composite(bg, im).convert("RGB")
    out = []
    for r, g, b in im.getdata():
        out.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))
    return out

def emit(cpp, h, ident, pixels):
    h.write(f"extern const uint16_t {ident}[{ICON * ICON}] PROGMEM;\n")
    cpp.write(f"const uint16_t {ident}[{ICON * ICON}] PROGMEM = {{\n")
    for i in range(0, len(pixels), 16):
        cpp.write("  " + ",".join(f"0x{p:04X}" for p in pixels[i:i + 16]) + ",\n")
    cpp.write("};\n\n")

def main():
    inc = ROOT / "include" / "assets.h"
    src = ROOT / "src" / "assets.cpp"
    with inc.open("w") as h, src.open("w") as cpp:
        h.write("// Generated by tools/gen_assets.py — do not edit.\n#pragma once\n#include <Arduino.h>\n\n")
        h.write(f"#define ICON_W {ICON}\n#define ICON_H {ICON}\n\n")
        cpp.write('// Generated by tools/gen_assets.py — do not edit.\n#include "assets.h"\n\n')
        for ident, rel in ACTIONS:
            emit(cpp, h, ident, to_rgb565(PLUGIN / rel))
        h.write("\n// App art, keyed by webOS app id\n")
        h.write("struct AppArt { const char* id; const uint16_t* icon; };\n")
        h.write(f"#define APP_ART_COUNT {len(APPS)}\nextern const AppArt APP_ART[APP_ART_COUNT];\n\n")
        for app in APPS:
            emit(cpp, h, cname(app), to_rgb565(PLUGIN / "apps" / f"{app}.png"))
        cpp.write("const AppArt APP_ART[APP_ART_COUNT] = {\n")
        for app in APPS:
            cpp.write(f'  {{"{app}", {cname(app)}}},\n')
        cpp.write("};\n")
    total = (len(ACTIONS) + len(APPS)) * ICON * ICON * 2
    print(f"wrote {len(ACTIONS)} action icons + {len(APPS)} app icons ({total // 1024} KB) -> {src.relative_to(ROOT)}, {inc.relative_to(ROOT)}")

if __name__ == "__main__":
    main()
